package com.examly.springapp;

import com.examly.springapp.model.CartModel;
import com.examly.springapp.model.ProductModel;
import com.examly.springapp.model.UserModel;
import com.examly.springapp.service.ProductService;
import com.examly.springapp.service.SignupService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.web.bind.annotation.CrossOrigin;

@Configuration
@SpringBootApplication(scanBasePackages = {"com.examly.springapp.**", "com.examly.springapp.service.**"})
@EnableJpaRepositories(basePackages = "com.examly.springapp.repository")
public class SpringappApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringappApplication.class, args);
	}

	@Bean
	CommandLineRunner run(@Autowired SignupService signupService, @Autowired ProductService productService) {
		return args -> {

			CartModel cartModel = new CartModel("0", "Admin Cart", "0", "0.0");
			signupService.saveUser(new UserModel("0", "admin@gmail.com", "admin", "admin", "9999999999", true, "admin", cartModel, null, false, ""));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/book/9/1/1/the-theory-of-everything-original-imadbgf6d45p2qzh.jpeg?q=100", "The Theory of Everything", "119.00", "A series of lectures made by Stephen Hawking in 1990s has been put together in the brilliant work called The Theory Of Everything which deals with all things Physics and more. In 1994, Stephen Hawking delivered seven lectures which was published in 1994 called Stephen W. Hawking's Life Works: The Cambridge Lectures. In 2002, an unauthorized version called The Theory Of Everything: The Origin and Fate of the Universe was released.", "200"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/k5vcya80/book/5/3/0/the-study-skills-book-original-imafzgtpnmdnxvhw.jpeg?q=100", "The Study Skills Book", "359.00", "The Study Skills book is an essential practical companion for students of any subject who want to improve their performance and succeed in their studies. It contains a wealth of tips and techniques for developing successful study skills and provides practical advice on everything from taking notes in lectures and time keeping, to writing and referencing essays and dissertations and proven revision techniques.", "150"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/jziqhzk0/book/4/0/2/aangalikana-pudhu-pudhu-udaigal-tailoring-guide-for-men-dresses-original-imafjgq8mxtfbkgh.jpeg?q=100", "You Can Win", "221.00", "Success is a hard commodity to obtain. However, like everything in our lives, it only needs careful planning, and deliberation. All success is deliberate, reveals Shiv Khera, and there is nothing magical about winning. Using common sense and varying lessons taken from ancient wisdom to modern philosophy, he shows how we can deal with issues of our daily lives, and how we can turn otherwise bad situations into good ones.", "189"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/kngd0nk0/book/r/h/y/indian-economy-for-civil-services-universities-and-other-original-imag24gmktdhnd4y.jpeg?q=100", "Indian Economy", "481.00", "More than a decade after its first publication, Indian Economy by Ramesh Singh continues to be as useful as ever and remains among the 'best-sellers' of all-time. One of the most recommended books on the subject, written by an expert with over two and a half decades of experience, it has emerged as an 'indispensable companion' for the aspirants of Civil Services exams.", "385"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/ki214sw0-0/book/k/q/m/chanakya-neeti-original-imafxxqmyzdea7qp.jpeg?q=100", "Chanakya Neeti", "192.00", "RADHAKRISHNAN PILLAI is the bestselling author of Corporate Chanakya, Chanakyas 7 Secrets of Leadership, Chanakya in You, Katha Chanakya and Thus Spoke Chanakya. He has researched Kautilyas Athashastra extensively and has a Masters degree in Sanskrit. A renowned management consultant and speaker, he is the Deputy Director of the Chanakya International Institute of Leadership Studies (CIILS) at the University of Mumbai.", "200"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/377/603/book/9/1/1/the-theory-of-everything-original-imadbgf6d45p2qzh.jpeg?q=100", "The Theory of Everything", "119.00", "A series of lectures made by Stephen Hawking in 1990s has been put together in the brilliant work called The Theory Of Everything which deals with all things Physics and more. In 1994, Stephen Hawking delivered seven lectures which was published in 1994 called Stephen W. Hawking's Life Works: The Cambridge Lectures. In 2002, an unauthorized version called The Theory Of Everything: The Origin and Fate of the Universe was released.", "60"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/book/9/1/1/the-theory-of-everything-original-imadbgf6d45p2qzh.jpeg?q=100", "The Theory of Everything", "119.00", "A series of lectures made by Stephen Hawking in 1990s has been put together in the brilliant work called The Theory Of Everything which deals with all things Physics and more. In 1994, Stephen Hawking delivered seven lectures which was published in 1994 called Stephen W. Hawking's Life Works: The Cambridge Lectures. In 2002, an unauthorized version called The Theory Of Everything: The Origin and Fate of the Universe was released.", "200"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/k5vcya80/book/5/3/0/the-study-skills-book-original-imafzgtpnmdnxvhw.jpeg?q=100", "The Study Skills Book", "359.00", "The Study Skills book is an essential practical companion for students of any subject who want to improve their performance and succeed in their studies. It contains a wealth of tips and techniques for developing successful study skills and provides practical advice on everything from taking notes in lectures and time keeping, to writing and referencing essays and dissertations and proven revision techniques.", "150"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/jziqhzk0/book/4/0/2/aangalikana-pudhu-pudhu-udaigal-tailoring-guide-for-men-dresses-original-imafjgq8mxtfbkgh.jpeg?q=100", "You Can Win", "221.00", "Success is a hard commodity to obtain. However, like everything in our lives, it only needs careful planning, and deliberation. All success is deliberate, reveals Shiv Khera, and there is nothing magical about winning. Using common sense and varying lessons taken from ancient wisdom to modern philosophy, he shows how we can deal with issues of our daily lives, and how we can turn otherwise bad situations into good ones.", "189"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/kngd0nk0/book/r/h/y/indian-economy-for-civil-services-universities-and-other-original-imag24gmktdhnd4y.jpeg?q=100", "Indian Economy", "481.00", "More than a decade after its first publication, Indian Economy by Ramesh Singh continues to be as useful as ever and remains among the 'best-sellers' of all-time. One of the most recommended books on the subject, written by an expert with over two and a half decades of experience, it has emerged as an 'indispensable companion' for the aspirants of Civil Services exams.", "385"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/ki214sw0-0/book/k/q/m/chanakya-neeti-original-imafxxqmyzdea7qp.jpeg?q=100", "Chanakya Neeti", "192.00", "RADHAKRISHNAN PILLAI is the bestselling author of Corporate Chanakya, Chanakyas 7 Secrets of Leadership, Chanakya in You, Katha Chanakya and Thus Spoke Chanakya. He has researched Kautilyas Athashastra extensively and has a Masters degree in Sanskrit. A renowned management consultant and speaker, he is the Deputy Director of the Chanakya International Institute of Leadership Studies (CIILS) at the University of Mumbai.", "200"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/377/603/book/9/1/1/the-theory-of-everything-original-imadbgf6d45p2qzh.jpeg?q=100", "The Theory of Everything", "119.00", "A series of lectures made by Stephen Hawking in 1990s has been put together in the brilliant work called The Theory Of Everything which deals with all things Physics and more. In 1994, Stephen Hawking delivered seven lectures which was published in 1994 called Stephen W. Hawking's Life Works: The Cambridge Lectures. In 2002, an unauthorized version called The Theory Of Everything: The Origin and Fate of the Universe was released.", "60"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/book/9/1/1/the-theory-of-everything-original-imadbgf6d45p2qzh.jpeg?q=100", "The Theory of Everything", "119.00", "A series of lectures made by Stephen Hawking in 1990s has been put together in the brilliant work called The Theory Of Everything which deals with all things Physics and more. In 1994, Stephen Hawking delivered seven lectures which was published in 1994 called Stephen W. Hawking's Life Works: The Cambridge Lectures. In 2002, an unauthorized version called The Theory Of Everything: The Origin and Fate of the Universe was released.", "200"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/k5vcya80/book/5/3/0/the-study-skills-book-original-imafzgtpnmdnxvhw.jpeg?q=100", "The Study Skills Book", "359.00", "The Study Skills book is an essential practical companion for students of any subject who want to improve their performance and succeed in their studies. It contains a wealth of tips and techniques for developing successful study skills and provides practical advice on everything from taking notes in lectures and time keeping, to writing and referencing essays and dissertations and proven revision techniques.", "150"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/jziqhzk0/book/4/0/2/aangalikana-pudhu-pudhu-udaigal-tailoring-guide-for-men-dresses-original-imafjgq8mxtfbkgh.jpeg?q=100", "You Can Win", "221.00", "Success is a hard commodity to obtain. However, like everything in our lives, it only needs careful planning, and deliberation. All success is deliberate, reveals Shiv Khera, and there is nothing magical about winning. Using common sense and varying lessons taken from ancient wisdom to modern philosophy, he shows how we can deal with issues of our daily lives, and how we can turn otherwise bad situations into good ones.", "189"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/kngd0nk0/book/r/h/y/indian-economy-for-civil-services-universities-and-other-original-imag24gmktdhnd4y.jpeg?q=100", "Indian Economy", "481.00", "More than a decade after its first publication, Indian Economy by Ramesh Singh continues to be as useful as ever and remains among the 'best-sellers' of all-time. One of the most recommended books on the subject, written by an expert with over two and a half decades of experience, it has emerged as an 'indispensable companion' for the aspirants of Civil Services exams.", "385"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/ki214sw0-0/book/k/q/m/chanakya-neeti-original-imafxxqmyzdea7qp.jpeg?q=100", "Chanakya Neeti", "192.00", "RADHAKRISHNAN PILLAI is the bestselling author of Corporate Chanakya, Chanakyas 7 Secrets of Leadership, Chanakya in You, Katha Chanakya and Thus Spoke Chanakya. He has researched Kautilyas Athashastra extensively and has a Masters degree in Sanskrit. A renowned management consultant and speaker, he is the Deputy Director of the Chanakya International Institute of Leadership Studies (CIILS) at the University of Mumbai.", "200"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/377/603/book/9/1/1/the-theory-of-everything-original-imadbgf6d45p2qzh.jpeg?q=100", "The Theory of Everything", "119.00", "A series of lectures made by Stephen Hawking in 1990s has been put together in the brilliant work called The Theory Of Everything which deals with all things Physics and more. In 1994, Stephen Hawking delivered seven lectures which was published in 1994 called Stephen W. Hawking's Life Works: The Cambridge Lectures. In 2002, an unauthorized version called The Theory Of Everything: The Origin and Fate of the Universe was released.", "60"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/book/9/1/1/the-theory-of-everything-original-imadbgf6d45p2qzh.jpeg?q=100", "The Theory of Everything", "119.00", "A series of lectures made by Stephen Hawking in 1990s has been put together in the brilliant work called The Theory Of Everything which deals with all things Physics and more. In 1994, Stephen Hawking delivered seven lectures which was published in 1994 called Stephen W. Hawking's Life Works: The Cambridge Lectures. In 2002, an unauthorized version called The Theory Of Everything: The Origin and Fate of the Universe was released.", "200"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/k5vcya80/book/5/3/0/the-study-skills-book-original-imafzgtpnmdnxvhw.jpeg?q=100", "The Study Skills Book", "359.00", "The Study Skills book is an essential practical companion for students of any subject who want to improve their performance and succeed in their studies. It contains a wealth of tips and techniques for developing successful study skills and provides practical advice on everything from taking notes in lectures and time keeping, to writing and referencing essays and dissertations and proven revision techniques.", "150"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/jziqhzk0/book/4/0/2/aangalikana-pudhu-pudhu-udaigal-tailoring-guide-for-men-dresses-original-imafjgq8mxtfbkgh.jpeg?q=100", "You Can Win", "221.00", "Success is a hard commodity to obtain. However, like everything in our lives, it only needs careful planning, and deliberation. All success is deliberate, reveals Shiv Khera, and there is nothing magical about winning. Using common sense and varying lessons taken from ancient wisdom to modern philosophy, he shows how we can deal with issues of our daily lives, and how we can turn otherwise bad situations into good ones.", "189"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/kngd0nk0/book/r/h/y/indian-economy-for-civil-services-universities-and-other-original-imag24gmktdhnd4y.jpeg?q=100", "Indian Economy", "481.00", "More than a decade after its first publication, Indian Economy by Ramesh Singh continues to be as useful as ever and remains among the 'best-sellers' of all-time. One of the most recommended books on the subject, written by an expert with over two and a half decades of experience, it has emerged as an 'indispensable companion' for the aspirants of Civil Services exams.", "385"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/ki214sw0-0/book/k/q/m/chanakya-neeti-original-imafxxqmyzdea7qp.jpeg?q=100", "Chanakya Neeti", "192.00", "RADHAKRISHNAN PILLAI is the bestselling author of Corporate Chanakya, Chanakyas 7 Secrets of Leadership, Chanakya in You, Katha Chanakya and Thus Spoke Chanakya. He has researched Kautilyas Athashastra extensively and has a Masters degree in Sanskrit. A renowned management consultant and speaker, he is the Deputy Director of the Chanakya International Institute of Leadership Studies (CIILS) at the University of Mumbai.", "200"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/377/603/book/9/1/1/the-theory-of-everything-original-imadbgf6d45p2qzh.jpeg?q=100", "The Theory of Everything", "119.00", "A series of lectures made by Stephen Hawking in 1990s has been put together in the brilliant work called The Theory Of Everything which deals with all things Physics and more. In 1994, Stephen Hawking delivered seven lectures which was published in 1994 called Stephen W. Hawking's Life Works: The Cambridge Lectures. In 2002, an unauthorized version called The Theory Of Everything: The Origin and Fate of the Universe was released.", "60"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/book/9/1/1/the-theory-of-everything-original-imadbgf6d45p2qzh.jpeg?q=100", "The Theory of Everything", "119.00", "A series of lectures made by Stephen Hawking in 1990s has been put together in the brilliant work called The Theory Of Everything which deals with all things Physics and more. In 1994, Stephen Hawking delivered seven lectures which was published in 1994 called Stephen W. Hawking's Life Works: The Cambridge Lectures. In 2002, an unauthorized version called The Theory Of Everything: The Origin and Fate of the Universe was released.", "200"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/k5vcya80/book/5/3/0/the-study-skills-book-original-imafzgtpnmdnxvhw.jpeg?q=100", "The Study Skills Book", "359.00", "The Study Skills book is an essential practical companion for students of any subject who want to improve their performance and succeed in their studies. It contains a wealth of tips and techniques for developing successful study skills and provides practical advice on everything from taking notes in lectures and time keeping, to writing and referencing essays and dissertations and proven revision techniques.", "150"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/jziqhzk0/book/4/0/2/aangalikana-pudhu-pudhu-udaigal-tailoring-guide-for-men-dresses-original-imafjgq8mxtfbkgh.jpeg?q=100", "You Can Win", "221.00", "Success is a hard commodity to obtain. However, like everything in our lives, it only needs careful planning, and deliberation. All success is deliberate, reveals Shiv Khera, and there is nothing magical about winning. Using common sense and varying lessons taken from ancient wisdom to modern philosophy, he shows how we can deal with issues of our daily lives, and how we can turn otherwise bad situations into good ones.", "189"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/kngd0nk0/book/r/h/y/indian-economy-for-civil-services-universities-and-other-original-imag24gmktdhnd4y.jpeg?q=100", "Indian Economy", "481.00", "More than a decade after its first publication, Indian Economy by Ramesh Singh continues to be as useful as ever and remains among the 'best-sellers' of all-time. One of the most recommended books on the subject, written by an expert with over two and a half decades of experience, it has emerged as an 'indispensable companion' for the aspirants of Civil Services exams.", "385"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/612/612/ki214sw0-0/book/k/q/m/chanakya-neeti-original-imafxxqmyzdea7qp.jpeg?q=100", "Chanakya Neeti", "192.00", "RADHAKRISHNAN PILLAI is the bestselling author of Corporate Chanakya, Chanakyas 7 Secrets of Leadership, Chanakya in You, Katha Chanakya and Thus Spoke Chanakya. He has researched Kautilyas Athashastra extensively and has a Masters degree in Sanskrit. A renowned management consultant and speaker, he is the Deputy Director of the Chanakya International Institute of Leadership Studies (CIILS) at the University of Mumbai.", "200"));
			productService.productSave(new ProductModel("", "https://rukminim1.flixcart.com/image/377/603/book/9/1/1/the-theory-of-everything-original-imadbgf6d45p2qzh.jpeg?q=100", "The Theory of Everything", "119.00", "A series of lectures made by Stephen Hawking in 1990s has been put together in the brilliant work called The Theory Of Everything which deals with all things Physics and more. In 1994, Stephen Hawking delivered seven lectures which was published in 1994 called Stephen W. Hawking's Life Works: The Cambridge Lectures. In 2002, an unauthorized version called The Theory Of Everything: The Origin and Fate of the Universe was released.", "60"));

		};
	}

	@Bean
	public BCryptPasswordEncoder passwordEncoder() {
		return new BCryptPasswordEncoder();
	}
}
